default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: <%= Figaro.env.database_name %>
  pool:     5
  password: <%= Figaro.env.database_password %>
  username: <%= Figaro.env.database_username %>
  template: template0

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
